"""Add is_online and auto_offline_time to Worker

Revision ID: 0193aaae017f
Revises: 3038b89059cb
Create Date: 2024-12-10 19:29:19.249670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0193aaae017f'
down_revision = '3038b89059cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'No description provided'"))
        batch_op.alter_column('rate_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'negotiable'"))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_offline_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('auto_offline_time')
        batch_op.drop_column('is_online')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('rate_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'negotiable'"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'No description provided'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
