"""Add skills table

Revision ID: 09963ccaed52
Revises: 201221bc5d34
Create Date: 2024-12-09 18:23:41.708066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09963ccaed52'
down_revision = '201221bc5d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=120), nullable=False),
    sa.Column('experience_level', sa.String(length=120), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    # ### end Alembic commands ###
