"""Add relationships to models

Revision ID: 201221bc5d34
Revises: 3460a0508cdb
Create Date: 2024-12-09 15:03:56.497326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201221bc5d34'
down_revision = '3460a0508cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
