"""empty message

Revision ID: 38368456724f
Revises: 1ebfba804c2a
Create Date: 2024-12-11 21:52:25.850329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38368456724f'
down_revision = '1ebfba804c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('travel_distance',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('travel_distance',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
